# Le format GeoJSON

GeoJSON est un format de données basé sur JSON, conçu pour représenter des objets géographiques simples et leurs propriétés associées. Il est largement utilisé dans les applications de cartographie web et les outils SIG modernes. Un fichier GeoJSON peut contenir des géométries (comme des points, des lignes, des polygones) et des propriétés (données attributaires). Par exemple, un point peut représenter une ville, avec des propriétés comme son nom ou sa population. GeoJSON est lisible par l'humain, facile à manipuler avec JavaScript, et compatible avec de nombreuses bibliothèques comme Leaflet, Maplibre GL ou Turf.js.


Voici à quoi ca ressemble : 

```{ojs}
//| echo: false
data = FileAttachment("data/world_209.geojson").json()
data
```

Dans jsfiddle, copiez le code suivant :

```{.js .custom-js}
fetch("https://raw.githubusercontent.com/neocarto/Webmapping/refs/heads/main/data/world_209.geojson")
.then(response => response.json())
.then(data => {
console.log(data)
}) 
```

Ou (autre syntaxe avec une fonction asynchrone anonyme)

```{.js .custom-js}
(async () => {
  const data = await (await fetch("https://raw.githubusercontent.com/neocarto/Webmapping/refs/heads/main/data/world_209.geojson")).json();
  console.log(data);
})();
```

# Manipuler un fichier geoJSON

Pour manipuler un geoJSON, on peut utiliser les fonctions JavaScript vues précédement.

Récupérer la première "feature"

```{.js .custom-js}
data.features[0]
```

Connaitre le nombre de pays

```{.js .custom-js}
data.features.length()
```

Par exemple, récupérer tous les codes ISO3

```{.js .custom-js}
data.features.map(d => d.properties.ISO3)
```
Ou récupérer toutes les géométries


```{.js .custom-js}
data.features.map(d => d.geometry)
```

Extraire un pays


```{.js .custom-js}
data.features.filter(d => d.properties.NAMEfr == "Cuba")
```


# Afficher un geoJSON

Pour afficher un geoJSON, on a besoin d'une bibliothèque JavaScript dédiée. Plusieurs options s'offrent à nous. Voici deux exemples :  

👉 **Avec Leaflet**

```{.html .custom-html}
<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
<link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
<div id="map"></div>
```

```{.js .custom-js}
fetch("https://raw.githubusercontent.com/neocarto/Webmapping/refs/heads/main/data/world_209.geojson")
.then(response => response.json())
.then(data => {
    const map = L.map('map');
    const layer = L.geoJSON(data).addTo(map);
    map.fitBounds(layer.getBounds(), { maxZoom: 9 });
}) 

```

```{.css .custom-css}
#map {
    height: 500px;
}
```


👉 **Avec geoviz**

```{.html .custom-html}
<script src="https://cdn.jsdelivr.net/npm/geoviz" charset="utf-8"></script>
<div id="map"></div>
```

```{.js .custom-js}
fetch("https://raw.githubusercontent.com/neocarto/Webmapping/refs/heads/main/data/world_209.geojson")
.then(response => response.json())
.then(data => {
const mapDiv = document.querySelector("#map");
let svg = geoviz.create({projection:"Mercator", width:500})
svg.path({data:data})
mapDiv.appendChild(svg.render());
})

```