# Turf.js


[Turf.js](https://turfjs.org/) est une bibliothèque JavaScript puissante et légère dédiée à l’analyse géospatiale (géotraitements). Elle permet de manipuler, transformer et analyser des données géographiques au format GeoJSON directement dans le navigateur ou dans un environnement Node.js. Avec Turf, on peut par exemple calculer des distances, des surfaces, des intersections, des buffers, des centroïdes, ou encore générer des grilles spatiales. Très utilisée dans les projets de cartographie interactive, notamment avec Leaflet ou Mapbox GL JS, Turf.js est précieuse pour effectuer des traitements spatiaux côté client sans avoir besoin d’un serveur SIG.

👉 **Documentation** : [https://turfjs.org](https://turfjs.org/)

Pour démarrer, commençons avec le code suivant : 

Copiez-le et exuctez-le dans jsfiddle.

```{.html .custom-html}
<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
<link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
<script src="https://cdn.jsdelivr.net/npm/@turf/turf@7/turf.min.js"></script>
<div id="titre">¡Hola, Cuba!</div>
<div id="map"></div>
```

```{.js .custom-js}
  // Coordonnées
  let coords = [
    [-75.1, 19.9], [-75.23, 19.9], [-77.74, 19.86], [-77.08, 20.47],
    [-78.07, 20.71], [-78.77, 21.64], [-79.9, 21.7], [-80.45, 22.07],
    [-81.82, 22.19], [-81.88, 22.68], [-82.78, 22.7], [-83.42, 22.19],
    [-84.52, 21.79], [-84.08, 22.67], [-82.22, 23.19], [-80.62, 23.09],
    [-78.68, 22.36], [-77.76, 21.81], [-76, 21.08], [-75.71, 20.69],
    [-74.77, 20.63], [-74.27, 20.07], [-75.1, 19.9]
  ];

  // Créer un GeoJSON avec Turf
  let cuba = turf.polygon([coords]);

  // Créer la carte Leaflet
  let map = L.map('map').setView([21.5, -79], 6);

  // Ajouter un fond OpenStreetMap
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; OpenStreetMap contributors'
  }).addTo(map);

  // Ajouter le polygone GeoJSON
  L.geoJSON(cuba, { color: 'orange', weight: 2, fillOpacity: 0.5 }).addTo(map);
```


 ```{.css .custom-css}
#map { width: 100%; height: 480px; }
#titre {font-size: 25px;                   /* taille assez grande */
  font-weight: bold;                 /* texte gras */
  color: #267A8A;                    /* couleur agréable */
  text-align: center; 
  }
 ```

 👉 Surface

 ```{.js .custom-js}
let area = turf.area(cuba);
console.log(area)
```

 👉 Centroid

 ```{.js .custom-js}
let center = turf.centroid(cuba)
console.log(center)
```

 👉 Buffer

```{.js .custom-js}
let buffer = turf.buffer(center, 500)
```

 👉 Intersection

```{.js .custom-js}
let intersection = turf.intersect(turf.featureCollection([cuba, buffer]));
```

 👉  Maintenant, calculons la distance entre deux points.


```{.js .custom-js}
const paris = [ 48.8534, 2.3488]
const vancouver = [49.2845, -123.1239]
const greatCircle = turf.greatCircle(paris.toReversed(), vancouver.toReversed(), {
  properties: { name: "de Paris à Vancouver" },
})
```

Créer une nouvelle carte leaflet, ajouter :

```{.js .custom-js}
L.marker(paris).addTo(map)
L.marker(vancouver).addTo(map)
L.geoJSON(greatCircle).addTo(map)
```

Calculer la longueur

```{.js .custom-js}
let length = turf.length(greatCircle, { units: "kilometers" });
console.log(length)
```

Voir à ce sujet : [le paradoxe de l'aviateur](https://www.humanite.fr/monde/regard-de-cartographe/le-paradoxe-de-laviateur)

::: {.callout-note title="Exercice"}

TODO

Calculer la distance entre le centroid de xxx et le centroid de yyyy


:::

TODO

Exemple de cartographie interactive.

Compter le nombre de points inclus dans le buffer.






# Geotoolbox

[Geotoolbox](https://riatelab.github.io/geotoolbox/) est une bibliothèque JavaScript développée pour faciliter la manipulation, l’analyse et la visualisation de données géographiques. Elle propose un ensemble d’outils modulaires destinés aux développeurs et aux cartographes, notamment pour le traitement de géométries en GeoJSON, la généralisation, le calcul d’indicateurs spatiaux, ou encore la mise en forme graphique de cartes. Pensée pour s’intégrer facilement dans des projets web, geotoolbox repose sur des standards ouverts et peut être utilisée en complément de bibliothèques comme D3.js ou MapLibre. 

👉 **Documentation** : [https://riatelab.github.io/geotoolbox/](https://riatelab.github.io/geotoolbox//)
